[tool.ruff]
line-length = 120
target-version = "py38"
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "env",
    "*.egg-info",
    "dist",
    "build"
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # line too long (handled by formatter)
]

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true
no_strict_optional = true
check_untyped_defs = false

[[tool.mypy.overrides]]
module = "anthropic.*"
ignore_missing_imports = true
