"""Initial schema with all tables

Revision ID: 76089491c4fe
Revises: 
Create Date: 2025-10-21 12:22:42.964052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76089491c4fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_setting_key'), ['setting_key'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.String(length=50), nullable=True),
    sa.Column('total_topics', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('analysis_path', sa.Text(), nullable=False),
    sa.Column('formatted_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_file_id'), ['file_id'], unique=True)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('key_terms_json', sa.Text(), nullable=True),
    sa.Column('regulatory_context', sa.Text(), nullable=True),
    sa.Column('pages', sa.String(length=50), nullable=True),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_question_type'), ['question_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic_id'), ['topic_id'], unique=False)

    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('topic_filter', sa.Text(), nullable=True),
    sa.Column('difficulty_filter', sa.String(length=50), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('pass_threshold', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('incorrect_answers', sa.Integer(), nullable=True),
    sa.Column('score_percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_session_type'), ['session_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_status'), ['status'], unique=False)

    op.create_table('spaced_repetition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=False),
    sa.Column('last_reviewed', sa.String(length=50), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('correct_reviews', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spaced_repetition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spaced_repetition_next_review_date'), ['next_review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_spaced_repetition_question_id'), ['question_id'], unique=True)

    op.create_table('user_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('selected_answer', sa.String(length=50), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('attempt_date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_attempts_attempt_date'), ['attempt_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_attempts_is_correct'), ['is_correct'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_attempts_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_attempts_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_attempts_session_id'))
        batch_op.drop_index(batch_op.f('ix_user_attempts_question_id'))
        batch_op.drop_index(batch_op.f('ix_user_attempts_is_correct'))
        batch_op.drop_index(batch_op.f('ix_user_attempts_attempt_date'))

    op.drop_table('user_attempts')
    with op.batch_alter_table('spaced_repetition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spaced_repetition_question_id'))
        batch_op.drop_index(batch_op.f('ix_spaced_repetition_next_review_date'))

    op.drop_table('spaced_repetition')
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_start_time'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_session_type'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_document_id'))

    op.drop_table('study_sessions')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_questions_question_type'))
        batch_op.drop_index(batch_op.f('ix_questions_document_id'))
        batch_op.drop_index(batch_op.f('ix_questions_difficulty'))

    op.drop_table('questions')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_file_id'))

    op.drop_table('documents')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_setting_key'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
